noun = input("Enter a noun: ")
color = input("Enter a color: ")
pet = input("Enter a pet: ")
food = input("Enter a food: ")
pluralNoun = input("Enter a pluralNoun: ")
adjective = input("Enter an adjective: ")
greetings = input("Enter a greetings: ")

print("Once upon a time, there lived a " + noun)
print(noun + " loved the " + color + " color")
print("He had a cute " + pet + " Everyday he feed his pet by " + food)
print("One day the mighty " + pluralNoun + " was watching the feeding " + pet)
print("She was so " + adjective)
print("She said " + greetings)
